version: "3.8"

volumes:
  orderapp:

services:
  order-service:
    container_name: order-service-c
    build:
      context: .
    ports:
      - "5003:5003"
    volumes:
      - orderapp:/orderapp
    restart: always
