version: "3.8"

volumes:
  bookapp:

services:
  book-service:
    container_name: book-service-c
    build:
      context: .
    ports:
      - "5002:5002"
    volumes:
      - bookapp:/bookapp
    restart: always
